### ISSUE TITLE
Error in installing R dependencies

### ISSUE THREAD

**Issue by swarnimshukla** [HelikarLab/candis#11]
When I am executing the command to install the R dependencies , it has some problem installing the Bioconductor. I am using ubuntu 16.04. 
 
![screenshot from 2018-02-16 17-55-34](https://user-images.githubusercontent.com/29918260/36307615-f95e4d7a-1342-11e8-8001-a7485e59469b.png)

**Comment by achillesrasquinha** [comment]
I feel you've got permission issues that fail to write your R dependencies. Can you check on that? Maybe this is not an issue candis could address.

**Comment by swarnimshukla** [comment]
Yeah it worked, thanks a lot
Closing this issue
