### ISSUE TITLE
Error in setup on Ubuntu

### ISSUE THREAD

**Issue by swarnimshukla** [HelikarLab/candis#14]
I am having a problem when I click on create a dataset.
The rows are not getting added immediately when I am clicking on the add rows button.
This is the console output of the event.
Can someone please help me out?
![jserror](https://user-images.githubusercontent.com/29918260/36631942-d890e3dc-19a5-11e8-815c-3e4809226a5e.png)

NOTE: Add a GIF/Screenshot if required.

**Comment by gopuvenkat** [comment]
Same issue in Linux mint 18.2 Sonya

**Comment by rupav** [comment]
As per https://github.com/HelikarLab/candis/blob/develop/.github/sample.gif , candis is able to work, load data, apply naive bayes algo on the same. But even after cloning CRES data, I am not able to load data on candis. 
I am getting the same error, and I am not even getting the option to `add` a row.

**Comment by rupav** [comment]
![screenshot from 2018-03-16 20-01-33](https://user-images.githubusercontent.com/20624380/37527506-32446f0e-2958-11e8-9c44-b83af22b4ae9.png)

**Comment by achillesrasquinha** [comment]
Looks like a `react-data-grid` error. Can you confirm what version you're using?

**Comment by rupav** [comment]
I am using Ubuntu 17.10

**Comment by achillesrasquinha** [comment]
`react-data-grid` within `node_modules`

**Comment by swarnimshukla** [comment]
It's 3.0.3

**Comment by gopuvenkat** [comment]
`react-data-grid` version : 3.0.11

**Comment by rupav** [comment]
@gopuvenkat  @swarnimshukla  it was indeed a react-data-grid error, feel free to reopen this issue, if encountered again.
Refer PR #57 
Closing this now.
