### ISSUE TITLE
Windows installation error.

### ISSUE THREAD

**Issue by arpits809** [HelikarLab/candis#15]
###pip installation error
pip doesn't recognize the Visual c++  version in the system even though i have visual c++ 2015 and have set the environment variables.
Error below:

C:\Users\Arpit\AppData\Local\Programs\Python\Python36>pip install candis
Collecting candis
  Using cached candis-0.0.5-py2.py3-none-any.whl
Requirement already satisfied: rpy2 in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from candis)
Collecting PyYAML (from candis)
  Using cached PyYAML-3.12.tar.gz
Requirement already satisfied: seaborn in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from candis)
Requirement already satisfied: matplotlib in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from candis)
Requirement already satisfied: pandas in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from candis)
Requirement already satisfied: Cython in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from candis)
Requirement already satisfied: requests in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from candis)
Collecting python-weka-wrapper3 (from candis)
  Using cached python-weka-wrapper3-0.1.4.tar.gz
Requirement already satisfied: django-htmlmin in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from candis)
Requirement already satisfied: Flask-SocketIO in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from candis)
Collecting pygraphviz (from candis)
  Using cached pygraphviz-1.3.1.zip
Requirement already satisfied: scipy in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from candis)
Requirement already satisfied: gunicorn in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from candis)
Requirement already satisfied: numpy in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from candis)
Requirement already satisfied: addict in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from candis)
Collecting javabridge (from candis)
  Using cached javabridge-1.0.15.tar.gz
Requirement already satisfied: Flask in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from candis)
Requirement already satisfied: Pillow in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from candis)
Requirement already satisfied: liac-arff in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from candis)
Requirement already satisfied: jinja2 in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from rpy2->candis)
Requirement already satisfied: six in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from rpy2->candis)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from matplotlib->candis)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from matplotlib->candis)
Requirement already satisfied: cycler>=0.10 in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from matplotlib->candis)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from matplotlib->candis)
Requirement already satisfied: pytz in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from matplotlib->candis)
Requirement already satisfied: idna<2.7,>=2.5 in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from requests->candis)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from requests->candis)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from requests->candis)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from requests->candis)
Requirement already satisfied: beautifulsoup4 in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from django-htmlmin->candis)
Requirement already satisfied: html5lib in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from django-htmlmin->candis)
Requirement already satisfied: python-socketio>=1.6.1 in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from Flask-SocketIO->candis)
Requirement already satisfied: click>=2.0 in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from Flask->candis)
Requirement already satisfied: Werkzeug>=0.7 in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from Flask->candis)
Requirement already satisfied: itsdangerous>=0.21 in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from Flask->candis)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from jinja2->rpy2->candis)
Requirement already satisfied: setuptools in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from kiwisolver>=1.0.1->matplotlib->candis)
Requirement already satisfied: webencodings in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from html5lib->django-htmlmin->candis)
Requirement already satisfied: python-engineio>=1.2.1 in c:\users\arpit\appdata\local\programs\python\python36\lib\site-packages (from python-socketio>=1.6.1->Flask-SocketIO->candis)
Installing collected packages: PyYAML, javabridge, python-weka-wrapper3, pygraphviz, candis
  Running setup.py install for PyYAML ... done
  Running setup.py install for javabridge ... error
    Complete output from command c:\users\arpit\appdata\local\programs\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Arpit\\AppData\\Local\\Temp\\pip-build-tw1be2wd\\javabridge\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Arpit\AppData\Local\Temp\pip-5_iszptg-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\javabridge
    copying javabridge\jutil.py -> build\lib.win-amd64-3.6\javabridge
    copying javabridge\locate.py -> build\lib.win-amd64-3.6\javabridge
    copying javabridge\noseplugin.py -> build\lib.win-amd64-3.6\javabridge
    copying javabridge\wrappers.py -> build\lib.win-amd64-3.6\javabridge
    copying javabridge\_version.py -> build\lib.win-amd64-3.6\javabridge
    copying javabridge\__init__.py -> build\lib.win-amd64-3.6\javabridge
    creating build\lib.win-amd64-3.6\javabridge\tests
    copying javabridge\tests\test_cpython.py -> build\lib.win-amd64-3.6\javabridge\tests
    copying javabridge\tests\test_javabridge.py -> build\lib.win-amd64-3.6\javabridge\tests
    copying javabridge\tests\test_jutil.py -> build\lib.win-amd64-3.6\javabridge\tests
    copying javabridge\tests\test_wrappers.py -> build\lib.win-amd64-3.6\javabridge\tests
    copying javabridge\tests\__init__.py -> build\lib.win-amd64-3.6\javabridge\tests
    creating build\lib.win-amd64-3.6\javabridge\jars
    copying javabridge\jars\cpython.jar -> build\lib.win-amd64-3.6\javabridge\jars
    copying javabridge\jars\rhino-1.7R4.jar -> build\lib.win-amd64-3.6\javabridge\jars
    copying javabridge\jars\runnablequeue.jar -> build\lib.win-amd64-3.6\javabridge\jars
    copying javabridge\jars\test.jar -> build\lib.win-amd64-3.6\javabridge\jars
    running build_ext
    C:\Program Files\Java\JDK18~1.0_1\bin\javac.exe -source 6 -target 6 C:\Users\Arpit\AppData\Local\Temp\pip-build-tw1be2wd\javabridge\java\org\cellprofiler\runnablequeue\RunnableQueue.java
    warning: [options] bootstrap class path not set in conjunction with -source 1.6
    1 warning
    C:\Program Files\Java\JDK18~1.0_1\bin\javac.exe -source 6 -target 6 C:\Users\Arpit\AppData\Local\Temp\pip-build-tw1be2wd\javabridge\java\org\cellprofiler\javabridge\test\RealRect.java
    warning: [options] bootstrap class path not set in conjunction with -source 1.6
    1 warning
    C:\Program Files\Java\JDK18~1.0_1\bin\javac.exe -source 6 -target 6 C:\Users\Arpit\AppData\Local\Temp\pip-build-tw1be2wd\javabridge\java\org\cellprofiler\javabridge\CPython.java C:\Users\Arpit\AppData\Local\Temp\pip-build-tw1be2wd\javabridge\java\org\cellprofiler\javabridge\CPythonInvocationHandler.java
    warning: [options] bootstrap class path not set in conjunction with -source 1.6
    Note: C:\Users\Arpit\AppData\Local\Temp\pip-build-tw1be2wd\javabridge\java\org\cellprofiler\javabridge\CPythonInvocationHandler.java uses unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.
    1 warning
    building 'javabridge._javabridge' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\arpit\appdata\local\programs\python\python36\lib\site-packages\numpy\core\include "-IC:\Program Files\Java\JDK18~1.0_1\include" "-IC:\Program Files\Java\JDK18~1.0_1\include\win32" -Ic:\users\arpit\appdata\local\programs\python\python36\include -Ic:\users\arpit\appdata\local\programs\python\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include" /Tc_javabridge.c /Fobuild\temp.win-amd64-3.6\Release\_javabridge.obj
    _javabridge.c
    c:\users\arpit\appdata\local\programs\python\python36\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.13.26128\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\users\arpit\appdata\local\programs\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Arpit\\AppData\\Local\\Temp\\pip-build-tw1be2wd\\javabridge\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Arpit\AppData\Local\Temp\pip-5_iszptg-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Arpit\AppData\Local\Temp\pip-build-tw1be2wd\javabridge\

**Comment by achillesrasquinha** [comment]
Kindly use the docker solution provided.
