### ISSUE TITLE
Unable to Download files from NCBI

### ISSUE THREAD

**Issue by majumderS** [HelikarLab/candis#165]
Hi, I was trying to download a dataset from the tool box download data option but I am unable to.
It is rendering a 401 "Email is incorrect" unauthorised response. 
I am supplying api-key, database as 'gds' and query terms as 'gpl'.

When I am trying to hit the entrez api end points through jupyter or browser, I am getting result. Any idea why this happening? 

![screenshot from 2019-03-01 22-21-00](https://user-images.githubusercontent.com/8430165/53635140-34a13900-3c42-11e9-98c8-f81a14788f08.png)

**Comment by achillesrasquinha** [comment]
I'm not sure if this has anything got to do with candis per se.
