### ISSUE TITLE
[BUG] Loading code from bind mounted volume

### ISSUE THREAD

**Issue by promehul** [HelikarLab/candis#166]
**Describe the bug**
What is happening now is that code is getting copied in the container when a container is started due to which container needs to be killed and restarted whenever we make a change in the code.

**Expected behavior**
On starting a container code should be mounted in the volume so that we don't need to restart container everytime we make change in the code.
So instead of `COPY . /app` we should use volume.

**Additional context**
I have started updating the Dockerfile. WIll send a PR as soon as possible.

**Comment by achillesrasquinha** [comment]
Hmm, I think it's best we structure out for development and production.

**Comment by achillesrasquinha** [comment]
Use COPY . /app for development, volume for production, Sounds good?

**Comment by promehul** [comment]
We should actually use volume in development so that changes are reflected in real time and use `COPY . /app` in production to ensure immutability and reproducibility.

**Comment by achillesrasquinha** [comment]
You know best! :)

**Comment by achillesrasquinha** [comment]
Create two compose files, ensure one overrides the other. Also try creating an `.env` directory for all variables included, again two seperate environments.

**Comment by achillesrasquinha** [comment]
https://github.com/pydanny/cookiecutter-django/ has an excellent approach towards maintaining multi-environments. Take a look at the bare-minimum boierlplate implmentation! It's a great upstart

**Comment by promehul** [comment]
> You know best! :)
Yes I will look into it and make the required changes .

**Comment by promehul** [comment]
Solved in #181
