### ISSUE TITLE
[BUG] Error on logging in, on docker.

### ISSUE THREAD

**Issue by promehul** [HelikarLab/candis#169]
**Describe the bug**
When I login both "logged in successfully" and "login first" toast appears.

**Expected behavior**
Only logged in successfully message should appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/32803738/54494405-c88c2980-48ff-11e9-8395-067371ba5776.png)

**Comment by rupav** [comment]
closing as its solved now. refer to https://github.com/HelikarLab/candis/pull/167
