### ISSUE TITLE
[BUG] Error on running a pipeline and using the candis-res data

### ISSUE THREAD

**Issue by promehul** [HelikarLab/candis#172]
**Describe the bug**
While running the pipeline in CLI mode,  I got an error  "rpy2.rinterface.RRuntimeError: Error in loadNamespace(name) : there is no package called 'affy'"

**To Reproduce**
1. import candis
2. cdata = candis.cdata.read('./candis-res/CRES/sample.cdata')
3. cdata.toARFF('./candis-res/CRES/iris.arff')

**Screenshots**
![image](https://user-images.githubusercontent.com/32803738/54774962-e674c980-4c32-11e9-803e-cc9566901d2d.png)

**Comment by promehul** [comment]
@achillesrasquinha  and @rupav  any clue?

**Comment by promehul** [comment]
I installed 'affy' in the container, then I am facing with this issue.
![image](https://user-images.githubusercontent.com/32803738/54779234-b0d4de00-4c3c-11e9-97b8-c559ae1c25e2.png)

**Comment by achillesrasquinha** [comment]
Have you installed the R dependencies? :)

**Comment by achillesrasquinha** [comment]
Is `get-candis` not working?

**Comment by promehul** [comment]
Will try to setup candis using get-candis script as well.
