### ISSUE TITLE
Getting error on login

### ISSUE THREAD

**Issue by rahul2240** [HelikarLab/candis#176]
**Describe the bug**
After sign up, I am redirected to my profile where I was asked to log in first.
During login, I am getting "Something bad happened.
I can confirm I am connected to db.

**To Reproduce**
1. Go to sign in
2. Click on sign in

**Expected behavior**
User should be able to log in.

**Screenshots**
![Screenshot from 2019-03-26 21-58-58](https://user-images.githubusercontent.com/25618739/55015300-9753dd80-5012-11e9-8371-f324d1d1f527.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - Browser : chrome

**Comment by promehul** [comment]
Are you using docker container?

**Comment by rahul2240** [comment]
@promehul no i am not.
