### ISSUE TITLE
Remove Options Menu

### ISSUE THREAD

**Issue by akram-mohammed** [HelikarLab/candis#19]
The options menu is blank.

**Comment by rupav** [comment]
@achillesrasquinha was it made initially for **user** settings - user profile, once we have database integration?

**Comment by rupav** [comment]
@akram-mohammed in the options menu, we have settings, which I have used as discussed with Achilles for default settings for the pipeline. Refer #147 . 
Update: For user settings, refer #125 .
So closing this issue now :)
