### ISSUE TITLE
App directory inside docker should have root access.

### ISSUE THREAD

**Issue by promehul** [HelikarLab/candis#193]
**Describe the bug**
App directory in docker has nobody:nogroup permissions when bind mounted. Because of it files cannot be changed from inside the docker.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by achillesrasquinha** [comment]
shouldn't
