### ISSUE TITLE
Change the Preprocess and Model arrow downward

### ISSUE THREAD

**Issue by akram-mohammed** [HelikarLab/candis#24]

**Comment by rupav** [comment]
Its showing downwards only,
Latest GIF showing this is:
![removepipe2](https://user-images.githubusercontent.com/20624380/40282823-722dfef6-5c92-11e8-8894-e453a0450b5f.gif)

As you can see, arrows are downward. This GIF is taken from PR #52 .
@akram-mohammed

**Comment by rupav** [comment]
Added an Invalid label as for now, please close if you feel it's not a problem now. @akram-mohammed

**Comment by rupav** [comment]
Closing it now, if came up again, will reopen this.
