### ISSUE TITLE
Add a feature to delete a pipeline

### ISSUE THREAD

**Issue by akram-mohammed** [HelikarLab/candis#27]
#### Steps to Reproduce:
*

NOTE: Add a GIF/Screenshot if required.

**Comment by rupav** [comment]
Claiming, once #30 gets merged, I will send a PR for this.

**Comment by rupav** [comment]
![removepipe](https://user-images.githubusercontent.com/20624380/39768504-17c4a990-5307-11e8-8d93-4eec8c2e07f5.gif)
@akram-mohammed this is done too. I will look Travis CI very soon (to get it working) to get PR #30  merged and then I will add this functionality too. Pipeline is deleted both from CRES directory and from redux-store/UI.
cc @achillesrasquinha .

**Comment by rupav** [comment]
Done @akram-mohammed  😃.
Now we have this feature, reference #52. 
Updated GIF:
![removepipe2](https://user-images.githubusercontent.com/20624380/40282823-722dfef6-5c92-11e8-8894-e453a0450b5f.gif) 

Closing this then.
