### ISSUE TITLE
Create a New Dataset is not working under Data tab

### ISSUE THREAD

**Issue by akram-mohammed** [HelikarLab/candis#28]

**Comment by rupav** [comment]
https://github.com/HelikarLab/candis/blob/b93a9bf12f38684d311da2d63efc700d77595f24/candis/app/client/app/component/widget/DataEditor.jsx#L139
So this prop, `rowSelection` is the cause of the error, http://adazzle.github.io/react-data-grid/examples.html#/row-select for documentation. I have opened the issue for the same in react-data-grid, waiting for their response.
