### ISSUE TITLE
Candis on Ubuntu using pip3 install

### ISSUE THREAD

**Issue by akram-mohammed** [HelikarLab/candis#6]
I am getting the following errors while installing candis using pip3 install.

amohammed@Akram:~$ pip3 install candis
Collecting candis
  Using cached candis-0.0.5-py2.py3-none-any.whl
Collecting pandas (from candis)
  Using cached pandas-0.21.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting numpy (from candis)
  Using cached numpy-1.13.3-cp35-cp35m-manylinux1_x86_64.whl
Collecting pygraphviz (from candis)
  Using cached pygraphviz-1.3.1.zip
Could not import setuptools which is required to install from a source distribution.
Please install setuptools.

amohammed@Akram:~$ pip3 install candis
Collecting candis
  Using cached candis-0.0.5-py2.py3-none-any.whl
Collecting django-htmlmin (from candis)
  Using cached django_htmlmin-0.10.0-py2.py3-none-any.whl
Collecting PyYAML (from candis)
  Downloading PyYAML-3.12.tar.gz (253kB)
    100% |████████████████████████████████| 256kB 707kB/s
Could not import setuptools which is required to install from a source distribution.
Please install setuptools.

amohammed@Akram:~$ pip3 install candis
Collecting candis
  Using cached candis-0.0.5-py2.py3-none-any.whl
Collecting numpy (from candis)
  Using cached numpy-1.13.3-cp35-cp35m-manylinux1_x86_64.whl
Collecting scipy (from candis)
Using cached scipy-1.0.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting liac-arff (from candis)
  Using cached liac-arff-2.1.1.tar.gz
Could not import setuptools which is required to install from a source distribution.
Please install setuptools.

amohammed@Akram:~$ pip3 install candis
Collecting candis
  Using cached candis-0.0.5-py2.py3-none-any.whl
Collecting addict (from candis)
  Using cached addict-2.1.1.tar.gz
Could not import setuptools which is required to install from a source distribution.
Please install setuptools.

amohammed@Akram:~$ pip3 install candis
Collecting candis
  Using cached candis-0.0.5-py2.py3-none-any.whl
Collecting Pillow (from candis)
  Downloading Pillow-4.3.0-cp35-cp35m-manylinux1_x86_64.whl (5.8MB)
    100% |████████████████████████████████| 5.8MB 129kB/s
Collecting javabridge (from candis)
  Using cached javabridge-1.0.15.tar.gz
Could not import setuptools which is required to install from a source distribution.
Please install setuptools.

amohammed@Akram:~$ pip3 install candis
Collecting candis
  Using cached candis-0.0.5-py2.py3-none-any.whl
Collecting Flask-SocketIO (from candis)
  Using cached Flask_SocketIO-2.9.3-py2.py3-none-any.whl
Collecting pandas (from candis)
  Using cached pandas-0.21.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting gunicorn (from candis)
  Using cached gunicorn-19.7.1-py2.py3-none-any.whl
Collecting python-weka-wrapper3 (from candis)
  Using cached python-weka-wrapper3-0.1.3.tar.gz
Could not import setuptools which is required to install from a source distribution.
Please install setuptools.

amohammed@Akram:~$ pip3 install candis
Collecting candis
  Using cached candis-0.0.5-py2.py3-none-any.whl
Collecting rpy2 (from candis)
  Using cached rpy2-2.9.1.tar.gz
Could not import setuptools which is required to install from a source distribution.
Please install setuptools.

amohammed@Akram:~$ pip3 install candis
Collecting candis
  Using cached candis-0.0.5-py2.py3-none-any.whl
Collecting scipy (from candis)
  Using cached scipy-1.0.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting pandas (from candis)
  Using cached pandas-0.21.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting javabridge (from candis)
  Using cached javabridge-1.0.15.tar.gz
Could not import setuptools which is required to install from a source distribution.
Please install setuptools.

amohammed@Akram:~$ pip3 install candis
Collecting candis
  Using cached candis-0.0.5-py2.py3-none-any.whl
Collecting PyYAML (from candis)
  Using cached PyYAML-3.12.tar.gz
Could not import setuptools which is required to install from a source distribution.
Please install setuptools.

**Comment by achillesrasquinha** [comment]
`pip3 install setuptools`?
