### ISSUE TITLE
Update CSS with Bootstrap 4

### ISSUE THREAD

**Issue by akram-mohammed** [HelikarLab/candis#7]
Bootswatch Updated to Bootstrap 4!!!

**Comment by achillesrasquinha** [comment]
:tear: They're still on a `beta` version. This can be a whole new port.

**Comment by achillesrasquinha** [comment]
Also, our dependencies aren't 4 compatible yet. We might need to review on the same.

**Comment by achillesrasquinha** [comment]
I'd wait a lot for this, maybe during their first minor versions. Closing this for now.
